### ISSUE TITLE
Annotated file input

### ISSUE THREAD

**Issue by aysunrhn** [labgem/PPanGGOLiN#25]
I'm trying to run the program with my own annotation files, but I can't seem to get it working right. So far I've tried:

1. To use only gbff files, so I wrote an input file that goes 
<organism name> <gbff file> 
which I input to the annot parameter. This resulted in an error in makeGraph.py as "NoneType object has no attribute removed"

2. To use both .fasta and .gff files so the input was:
<organism name> <fasta file> <gff file> 
again, using only the annot parameter

3. Finally I tried giving fasta and gbff files separately to --fasta and --anno options but I ended up with the same error as in 1.

I have went over the example input files in testingDataset directory, but I can't see where I got it wrong. Also, apart from this issue, I was wondering if it is possible to retain the annotations your own pipeline generates?

**Comment by axbazin** [comment]
It sounds like the annotation files were not properly read. I will try to look into it.

How did you generate those annotation files ? Could I eventually download them/ get them so I can reproduce the error ? (if that's possible you can send some of them to me at abazin at genoscope dot cns dot fr).

It is possible to retain the annotations, however not in a practical format for now. If you run : 

`ppanggolin write -p myPangenome.h5 --output myoutputdir --projection`

You will get a folder called 'projection' with one file for each genome. Those file are in a .tsv format, and each column's value is described here : https://github.com/labgem/PPanGGOLiN/wiki/Outputs#projection

**Comment by aysunrhn** [comment]
> It sounds like the annotation files were not properly read. I will try to look into it.
> 
> How did you generate those annotation files ? Could I eventually download them/ get them so I can reproduce the error ? (if that's possible you can send some of them to me at abazin at genoscope dot cns dot fr).

Thanks! I was simply using the annotations from NCBI, I retrieved .gbff.gz files: ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/003/012/895/GCA_003012895.2_ASM301289v2

I have renamed them with strain names though, but all the file names match and I didn't have any issues when I used .fasta files only. Some strain names have "-" in them, would that be an issue?

> It is possible to retain the annotations, however not in a practical format for now. If you run :
> 
> `ppanggolin write -p myPangenome.h5 --output myoutputdir --projection`
> 
> You will get a folder called 'projection' with one file for each genome. Those file are in a .tsv format, and each column's value is described here : https://github.com/labgem/PPanGGOLiN/wiki/Outputs#projection

Thank you, I will look into that!

**Comment by axbazin** [comment]
The names should not be a problem, especially since it worked with --fasta.

I downloaded the files for complete genomes of Acinetobacter baumannii and I think I found the origin of the problem, I will try to solve it and push the changes when it works.

**Comment by axbazin** [comment]
The fixes I pushed to github today might solve your issue.
if you want to reinstall ppanggolin with the fixes and if you installed it previously with conda, you can clone the repo, go to its root and, with the conda environment activated run :

pip install .

It should use conda's version of pip, and it should remove the current version of PPanGGOLiN that was installed by conda and replace it with the new one.

Could you try it out with what you tried first, using the .gbff files only ? If it does not work could you send me or attach to the issue the ORGANISMS_ANNOTATION_LIST file that you made so that I can take a closer look at it ?

And if it does work, please let me know.

**Comment by aysunrhn** [comment]
Thank you for such quick response. I have downloaded your last update, but I'm still getting the same error (in all 3 cases I outlines above). So here's what my annotation file looks like:

```bash
$ head annot-gbff.txt
NCGM-237.gbff	<full-path-to-the-directory>/gbk/NCGM-237.gbff.gz
IOMTU-433.gbff	<full-path-to-the-directory>/gbk/IOMTU-433.gbff.gz
AB307-0294.gbff	<full-path-to-the-directory>/gbk/AB307-0294.gbff.gz
BJAB07104.gbff	<full-path-to-the-directory>/gbk/BJAB07104.gbff.gz
BJAB0715.gbff	<full-path-to-the-directory>/gbk/BJAB0715.gbff.gz
BJAB0868.gbff	<full-path-to-the-directory>/gbk/BJAB0868.gbff.gz
TYTH-1.gbff	<full-path-to-the-directory>/gbk/TYTH-1.gbff.gz
AC29.gbff	<full-path-to-the-directory>/gbk/AC29.gbff.gz
AC30.gbff		<full-path-to-the-directory>/gbk/AC30.gbff.gz
AB5075-UW.gbff		<full-path-to-the-directory>/gbk/AB5075-UW.gbff.gz
```
Just replaced the path when I pasted into this message btw. I'm also sending the NCGM-237.gbff.gz file attached, which is exactly the version I downloaded from NCBI.
[NCGM-237.gbff.gz](https://github.com/labgem/PPanGGOLiN/files/3890606/NCGM-237.gbff.gz)

**Comment by axbazin** [comment]
I managed to reproduce your error, it is related to the locus_tag field in .gbff files. We use what is written in this field as a unique gene identifier, and in some genomes the content of that field is not unique which introduces problems.

After careful examination it was obviously a mistake to do that since nothing forces genbank submitters to assign unique values to the locus_tag field, even if it is unique most of the time. We do not use the genome annotations from GenBank in our analyses so we did not notice this problem before.

In my testings this appeared only when using the genome annotations from GenBank. When I downloaded the RefSeq versions of some of the problematic genome annotations I had no problem and it raised no error.

I'll update the code so that we stop relying on locus_tag but that might take a few days.

**Comment by aysunrhn** [comment]
Ok I see now, thank you for the explanation. Can you point out the files that had this issue as an example? 

I could try modifying the locus tags to include the accession number, or make it unique in a different way.

**Comment by axbazin** [comment]
Yes of course.

GCA_002727055.2 has the problem of having identical 'locus_tag' between different contigs.
(example locus_tag 'CPI82_00005' is found on contig 'NXDV01000001' and on contig 'CP027483').

Another example with different genomes using the same 'locus_tag' base, like those five genomes that seem to be from the same project : 
GCA_900176685.1
GCA_900175175.1
GCA_900175185.1
GCA_900175195.1
GCA_900176715.1

The RefSeq versions of those genomes include unique locus_tags however, so you could just use RefSeq genome annotations instead of GenBank ones as a solution.
Including the accession number in the locus_tag is definitely a good strategy for those cases. Making it unique in any other ways would solve the problem too.

**Comment by aysunrhn** [comment]
I thought I was already using the RefSeq versions actually but I just checked again and I think with all the genomes the GenBank and RefSeq entries are identical except for 2 strains. Too bad a RefSeq version is available for them, so I will edit those two files only and try again.

**Comment by axbazin** [comment]
Alright, I hope it goes well.
The current version of PPanGGOLiN on github might work with your dataset now, I (hopefully) removed the need of having unique 'locus_tag', but we have not tested the version extensively yet. It did work on the dataset which had the genomes I mentionned previously.

**Comment by aysunrhn** [comment]
I have fixed the annotation files and it seems to work now. Again, thank you for looking into the problem!
